name: nopeek
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.7.*
  - numpy
  - pytorch==1.4.*
  - torchvision
  - cpuonly
  - matplotlib
  - jupyterlab==2.1.*  # version to be compatible with PySyft
# utilities
  - tqdm
  - pip >= 19
  - pip:
      - syft[udacity]
